### PR TITLE
Dev emily

### PR DESCRIPTION
**Pull request by WhiteWolfdoge**
Working version

### CODE REVIEW

**Comment by WhiteWolfdoge** [comment]
RELEASE 0.1

**Comment by WhiteWolfdoge** [comment]
v0.2-RELEASE
Added remove feature

**Comment by TylerS1066** [comment]
So long as spark is fine with this I will merge it.

**Comment by WhiteWolfdoge** [comment]
Already at v0.5-RELEASE
Pretty sweet!

**Comment by TylerS1066** [comment]
Merged

**Pull request merged**
